### ISSUE TITLE
환경설정

### ISSUE THREAD

**Issue by nohgijin** [woowa-techcamp-2020/market-park-noh#1]
- [x] Node.js 버전 맞추기(v12.18.2)
- [x] 패키지 관리는 npm으로
- [x] node_modules gitignore하기
- [x] 템플릿 엔진은 pug로(v3.0.0)

**Comment by parkjihwanjay** [comment]
resolve 89c7c78

**Comment by parkjihwanjay** [comment]
resolve 89c7c78
